FROM python:3.6

EXPOSE 4000
WORKDIR /app

COPY templates /app/templates
COPY static /app/static
COPY model /app/model
COPY requirements.txt /app
COPY app.py /app

RUN pip install -r requirements.txt
CMD python app.py